services:
  db:
    image: postgres:16
    container_name: petstyle-db
    environment:
      POSTGRES_USER: petstyle
      POSTGRES_PASSWORD: petstyle123
      POSTGRES_DB: petstyle
    ports:
      - "5432:5432"
    volumes:
      - petstyle_data:/var/lib/postgresql/data

volumes:
  petstyle_data: